slack:
  webhook_url: $SLACK_WEBHOOK_URL

rpc_url:
  eth_goerli: $ETH_GOERLI_RPC_URL
  eth_mainnet: $ETH_MAINNET_RPC_URL
  eth_sepolia: $ETH_SEPOLIA_RPC_URL
  gnosis_mainnet: $GNOSIS_MAINNET_RPC_URL
  gnosis_testnet: $GNOSIS_TESTNET_RPC_URL
  polygon_mainnet: $POLYGON_MAINNET_RPC_URL

mongo:
  uri: $MONGO_URI
  db: file-storage

logger:
  format: json
  level: debug

pinata:
  jwt: $PINATA_JWT
  host: https://api.pinata.cloud
  unpin_path: pinning/unpinp
  pin_path: pinning/pinFileToIPFS

x_api_key: "hello_world"
fileverse_gateway: "https://ipfs.fileverse.io/ipfs/"
port: 8001
