slack:
  webhook_url: $SLACK_WEBHOOK_URL

rpc_url:
  eth_goerli: ""
  eth_mainnet: ""
  eth_sepolia: ""
  gnosis_mainnet: ""
  gnosis_testnet: ""
  polygon_mainnet: ""

mongo:
  uri: $MONGO_URI
  db: storage

logger:
  format: json
  level: debug

pinata:
  api_key: $PINATA_API_KEY
  secret: $PINATA_SECRET
  jwt: $PINATA_JWT
  host: https://api.pinata.cloud
  unpin_path: pinning/unpinp
  pin_path: pinning/pinFileToIPFS

x_api_key: "hello_world"
fileverse_gateway: "https://ipfs.fileverse.io/ipfs/"
